name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

  

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8

  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_form_builder: ^9.3.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf
          weight: 700